### ISSUE TITLE
[Question] Kibana with enhanced-table running on Kubernetes

### ISSUE THREAD

**Issue by ovidiaconescu** [fbaligand/kibana-enhanced-table#228]
I'm trying to install Kibana with a plugin via the [initContainers](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-init-containers-plugin-downloads.html) functionality and it doesn't seem to create the pod with the plugin in it.

The pod gets created and Kibana works perfectly, but the plugin is not installed using the yaml below.

```
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
spec:
  version: 7.11.2
  count: 1
  elasticsearchRef:
    name: quickstart
  podTemplate:
    spec:
      initContainers:
      - name: install-plugins
        command:
        - sh
        - -c
        - |
          bin/kibana-plugin install https://github.com/fbaligand/kibana-enhanced-table/releases/download/v1.11.2/enhanced-table-1.11.2_7.11.2.zip
```
